### ISSUE TITLE
Create dummy rest data for usage by FE

### ISSUE THREAD

**Issue by yohny** [ERNICommunity/hh-dust-fe-be#1]
provide to FE guys following REST endpoints:
- [ ] api/sensors (list sensors with location and latest dust levels)
- [ ] api/sensors/{sensorId}/history (historical data for given sensor)
- [ ] api/sensors/{sensorId}/prediction (prediction for given sensors)

**Comment by matwej** [comment]
yeah, and then the query params would be:
- api/sensors/{sensorId}/history?from=[timestamp] ( to is not defined as for now, it's till current time)
- api/sensors/{sensorId}/prediction?to=[timestamp] (from is current time)

also we need to agree later on response codes = f.e. /history?from=[so much to past] -> return error which would tell that it is too much to the past ... and so on

**Comment by matwej** [comment]
should those params be optional (and default would be one day for example), or mandatory?

**Comment by yohny** [comment]
I prefer mandatory so we are explicit on the API
